### ISSUE TITLE
rootFolderName get faild

### ISSUE THREAD

**Issue by Laurie-Lin** [RatakondalaArun/shelf_virtual_directory#15]
when i use this code to get handler.
```dart
final virDirHandler = ShelfVirtualDirectory('/').handler;
```
and exec shelf io.server(virDirHandler,xxx,xxx);
it will crash in `virtual_directory.dart` line 99
```
    final rootFolderName = ([..._rootDir.uri.pathSegments]..removeLast()).last;
```
because `_rootDir.uri.pathSegments` is empty list.

**Comment by RatakondalaArun** [comment]
Hello @Nightmare-MY are you trying to serve root folder in a system?

**Comment by RatakondalaArun** [comment]
@Nightmare-MY It is possible that you provide me with logs? Since I am unable to reproduce it on my side.

**Comment by Laurie-Lin** [comment]
Yes I'm trying to service my root directory,i had to do that,i edit code like this:
```dart
    var rootFolderName;
    if (folderPath == '/') {
      rootFolderName = '/';
    } else {
      rootFolderName = ([..._rootDir.uri.pathSegments]..removeLast()).last;
    }
```
That works fine.
and I discovered something will be get problem
```dart
    final rootDirSubFolders = await _rootDir.list(recursive: false).toList();
```
for example my rootdir is '/',this code will be crashed because it doesn't have permissions on some files,
and i find `shelf_static` worked fine.

**Comment by RatakondalaArun** [comment]
@Nightmare-MY  as you said it is happening because of a permission error I will try to fix this but requires a huge refactor.
