### ISSUE TITLE
New files does not get served untill application restart

### ISSUE THREAD

**Issue by timotheux** [RatakondalaArun/shelf_virtual_directory#16]
I noticed that static files (for example images) added to the virtual directory while the application is already running does not get served until you restart the application again. I am using shelf_virtual_directory version 2.0.0 on Windows 10. My application was compiled to a console exe and running as a windows service.

Cheers

**Comment by RatakondalaArun** [comment]
@timotheux Currently working on #15 once this is closed it will solve this issue

**Comment by timotheux** [comment]
@RatakondalaArun is there any progress on this?

Keep up the good work.

Cheers

**Comment by RatakondalaArun** [comment]
Hello @timotheux, got busy with some other work. You can expect a fix by next weekend. 🥂

**Comment by RatakondalaArun** [comment]
#17 closed #16

**Comment by timotheux** [comment]
Nice work @RatakondalaArun I will check this out and give you a feedback tomorrow.

Cheers!

**Comment by RatakondalaArun** [comment]
Thank you @timotheux 

Would love to hear your feedback.
